portfolio/home/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from home import views

app_name ='home'
urlpatterns = [
    #/home/
    path('', views.IndexClassView.as_view(), name='home' ),
    #/home/
    path('<int:pk>/',views.FoodDetail.as_view(),name='detail'),
    path('security', views.security, name='security'),

    #adding items 
    path('add',views.createItem.as_view(), name ='create_item'),       
    #for editing
    path('update/<int:id>/',views.update_item,name='update_item'),

    #for delete
    path('delete/<int:id>',views.delete_item,name='delete_item')
]

portfolio/portfolio/urls.py
from django.contrib import admin
from django.urls import path, include  
from users import views as user_views
from django.contrib.auth import views as authentication_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('register/',user_views.register,name='register'),
    path('login/',authentication_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',authentication_views.LoginView.as_view(template_name='users/logout.html'),name='logout'),
    path('profile/',user_views.profilepage,name='profile',)

]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

portfolio/home/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.
class Item(models.Model):

    def __str__(self):
        return self.item_desc
    user_name = models.ForeignKey(User,on_delete=models.CASCADE,default=1)
    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_image = models.CharField(max_length=600, default="https://s3.amazonaws.com/ODNUploads/532dfdbcc6479placeholder_food_item_2.png") 

    def get_absolute_url(self):
            return reverse("home:detail", kwargs={"pk": self.pk})

portfolio/users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    image = models.ImageField(default='profilepic.jpg',upload_to='profile_picture')
    location = models.CharField(max_length=200)

    def _str_(self):
        return self.user.username

portfolio/home/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = {'item_name','item_desc','item_image','item_price'}

portfolio/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
    email = forms.EmailField()
    

    class Meta:
        model = User
        fields = ['username','email','password1','password2']

portfolio/home/views.py
from django import forms
from django.http.response import HttpResponse
from django.shortcuts import redirect, render, HttpResponse
from .models import Item
from django.template import loader
from .forms import ItemForm
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView


# Create your views here.
def index(request):
    item_list = Item.objects.all()
    
    context ={
        'item_list':item_list,
    }
    return render(request,'home/index.html',context)


class IndexClassView(ListView):
    model = Item;
    template_name = 'home/index.html'
    context_object_name = 'item_list'
    

def security(request):
    return HttpResponse("this is security")


def detail(request,item_id):
    item=Item.objects.get(pk=item_id)
    context ={
        'item':item,
    }
    return render(request,'home/detail.html',context)

class FoodDetail(DetailView):
    model = Item
    template_name = 'home/detail.html'

def create_item(request):
    form = ItemForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect('home:home')
    
    return render(request, "home/item-form.html", {'form':form})


#this is a class based view for create view
class CreateItem(CreateView):
    model = Item;
    fields = ['item_name','item_desc', 'item_price', 'item_image']
    template_name = 'home/detail.html'


    def form_valid(self,form):
        form.instance.user_name = self.request.user

        return super().form_valid(form)




def update_item(request,id):
    item = Item.objects.get(id=id)
    form = ItemForm(request.POST or None, instance=item)

    if form.is_valid():
        form.save()
        return redirect('home:home')
        
    return render(request,'home/item-form.html',{'form':form,'item':item})

def delete_item(request,id):
    item = Item.objects.get(id=id)


    if request.method == 'POST':
        item.delete()
        return redirect('home:home')

    return render(request,'home/item-delete.html',{'item':item})

portfolio/users/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import RegisterForm
# Create your views here.



def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success (request,f'welcome {username}, your account is created')
            return redirect ('login')
    else:
    
        form =RegisterForm
    return render (request,'users/register.html',{'form':form})


@login_required
def profilepage(request):
    return render(request,'users/profile.html')

portfolio/home/templates/home/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Document</title>
    <!-- <Link rel="stylesheet" href="{% static 'home/style.css' % }"> -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
        <a href="#" class="navbar-brand"> Portfolio </a>"
         
        <div class="navbar">
            <a class="nav-item nav-link" href="{% url 'home:create_item' %}" > Home</a>
            <a class="nav-item nav-link" href="#"> Contact us</a>
            <a class="nav-item nav-link" href="#"> About</a>
            <a class="nav-item nav-link" href="#"> Skills</a>
            {% if user.is_authenticated %}
            <a href="{% url 'logout' %}">Logout</a>
            <a href="{% url 'profile' %}">Profile</a>

            {% else %}
                <a href="{% url 'logout' %}">Login</a>
            {% endif %}
        </div>
    </nav>
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tag }}"> {{ message }}</div>
            
        {% endfor %}
    {% endif %}

    {% block body %}
    {% endblock %}
</body>
</html>

portfolio/home/templates/home/detail.html
{% extends 'home/base.html' %}
{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-5">
            <img src="{{ item.item_image }}" alt="" class="img-fluid" style="height:200; object-fit:cover;">
        </div>
        <div class="col-md-5">
            <h1>{{object.item_name}}</h2>
            <h2>{{object.item_desc}}</h2>
            <h3>{{object.item_price}}</h3>
            <a href="{% url 'home:delete_item' item.id %}">Delete</a>
        </div>
    </div>
</div>
{% endblock %}

portfolio/home/templates/home/index.html
{% extends 'home/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">


</head>
<body>
    {% block body %}
    {% for item in item_list %}   
    <div class="row"> 
      <div class="col-md-3 offset-md-2">
        <img src="{{ item.item_image }}" alt="" class="img-fluid" style="height:200; object-fit:cover;">
      </div>

      <div class="col-md-4">
        <h3>{{ item.item_name}}</h3>
        <p class="mt-3">Price: Rs.{{item.item_price}}</p>
        <p class="mt-3">{{item.item_desc}}</p>
      </div>

      <div class="col-md-2">
        <a href="{% url 'home:detail' item.id %}" class="btn btn-primary"> Details </a>           
      </div>

    </div>


    {% endfor %}
    
   

   

    {% endblock %}

</body>
</html>

portfolio/home/templates/home/item-delete.html
<form method="POST">
    {% csrf_token %}
    <h2>Are you sure want t delete {{ item.item_name }}</h2>
    <button type="submit">Confirm</button>
</form>

portfolio/home/templates/home/item-form.html
{% extends 'home/base.html' %}
{% block body %}
<form method="POST">
    {% csrf_token %}
    {{form}}
    <button type="submit">save</button>

</form>
{% endblock %}

portfolio/users/templates/users/login.html
<form method="POST">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Login</button>
</form>

portfolio/users/templates/users/logout.html
<h1>You have been loged out</h1>

portfolio/users/templates/users/profile.html
<h1>
    {{ user.username  }}
</h1>
<img width="100px" height="100px"src="{{ user.profile.image.url }}" >

<h1>
    {{ user.profile.location }}  
</h1>

portfolio/users/templates/users/register.html
<form method="POST">
    {% csrf_token %}
    {{ form }}
    <button type="submit">signup</button>
</form>